# FreshHarvest Data Parameters
# Specific parameters for data processing and handling

# Dataset Information
dataset_info:
  name: "FreshHarvest"
  version: "1.0"
  description: "Fruit freshness classification dataset - 96.50% accuracy"
  total_classes: 6
  image_count: 12000
  target_accuracy: 0.965

# Data Splits
data_splits:
  train_ratio: 0.7
  validation_ratio: 0.2
  test_ratio: 0.1
  random_seed: 42
  stratify: true

# Image Parameters
image_params:
  # Target dimensions
  height: 224
  width: 224
  channels: 3

  # Format specifications
  format: "RGB"
  dtype: "float32"

  # Normalization
  normalize: true
  mean: [0.485, 0.456, 0.406]  # ImageNet means
  std: [0.229, 0.224, 0.225]   # ImageNet stds

  # Quality constraints
  min_resolution: [32, 32]
  max_resolution: [2048, 2048]
  min_file_size: 1024  # bytes
  max_file_size: 10485760  # 10MB

# Data Augmentation Parameters
augmentation_params:
  # Geometric transformations
  rotation_range: 20
  width_shift_range: 0.2
  height_shift_range: 0.2
  shear_range: 0.2
  zoom_range: [0.8, 1.2]

  # Flipping
  horizontal_flip: true
  vertical_flip: false

  # Color transformations
  brightness_range: [0.8, 1.2]
  contrast_range: [0.8, 1.2]
  saturation_range: [0.8, 1.2]
  hue_range: [-0.1, 0.1]

  # Noise and blur
  gaussian_noise_std: 0.01
  gaussian_blur_sigma: [0.1, 2.0]

  # Advanced augmentations
  cutout_prob: 0.2
  cutout_size: [16, 32]
  mixup_alpha: 0.2
  cutmix_alpha: 1.0

# Class Information
class_info:
  # Fresh fruits (0-2)
  fresh_fruits:
    Fresh_Apple: 0
    Fresh_Banana: 1
    Fresh_Orange: 2

  # Rotten fruits (3-5)
  rotten_fruits:
    Rotten_Apple: 3
    Rotten_Banana: 4
    Rotten_Orange: 5

  # Class mapping for 96.50% accuracy model
  class_names:
    0: "Fresh Apple"
    1: "Fresh Banana"
    2: "Fresh Orange"
    3: "Rotten Apple"
    4: "Rotten Banana"
    5: "Rotten Orange"

  # Freshness categories
  freshness_mapping:
    fresh_classes: [0, 1, 2]
    rotten_classes: [3, 4, 5]

# Data Loading Parameters
loading_params:
  batch_size: 32
  shuffle_buffer_size: 1000
  prefetch_buffer_size: 2
  num_parallel_calls: 4

  # Memory optimization
  cache_dataset: false
  use_memory_mapping: true

# Data Validation Parameters
validation_params:
  # Image validation
  check_image_integrity: true
  check_image_format: true
  check_image_size: true

  # Class balance validation
  check_class_balance: true
  min_samples_per_class: 50
  max_class_imbalance_ratio: 0.1

  # Data quality checks
  check_duplicates: true
  check_corrupted_files: true
  similarity_threshold: 0.95

# Export Parameters
export_params:
  # TFRecord export
  tfrecord_compression: "GZIP"
  tfrecord_shard_size: 1000

  # HDF5 export
  hdf5_compression: "gzip"
  hdf5_compression_level: 9

  # Metadata export
  export_metadata: true
  metadata_format: "json"