version: '3.8'

services:
  # FreshHarvest Production Application
  freshharvest-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: freshharvest-app-prod
    ports:
      - "80:8501"  # Production port mapping
    volumes:
      - ./artifacts:/app/artifacts:ro
      - ./logs:/app/logs
      - ./monitoring/logs:/app/monitoring/logs
      - ./data:/app/data:ro
    environment:
      - PYTHONPATH=/app
      - STREAMLIT_SERVER_PORT=8501
      - STREAMLIT_SERVER_ADDRESS=0.0.0.0
      - MODEL_TARGET_ACCURACY=0.965
      - ENVIRONMENT=production
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8501/_stcore/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s
    networks:
      - freshharvest-prod-network
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: 4G
        reservations:
          cpus: '1.0'
          memory: 2G

  # Production Redis Cache
  redis:
    image: redis:7-alpine
    container_name: freshharvest-redis-prod
    volumes:
      - redis_prod_data:/data
      - ./config/redis.conf:/usr/local/etc/redis/redis.conf:ro
    restart: always
    networks:
      - freshharvest-prod-network
    command: redis-server /usr/local/etc/redis/redis.conf
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M

  # Production Monitoring
  monitoring:
    build:
      context: .
      dockerfile: Dockerfile.monitoring
    container_name: freshharvest-monitoring-prod
    ports:
      - "8080:8502"  # Monitoring dashboard
    volumes:
      - ./monitoring/logs:/app/monitoring/logs
      - ./logs:/app/logs:ro
    environment:
      - PYTHONPATH=/app
      - STREAMLIT_SERVER_PORT=8502
      - ENVIRONMENT=production
    restart: always
    depends_on:
      - freshharvest-app
    networks:
      - freshharvest-prod-network
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 2G

  # Nginx Reverse Proxy (Production)
  nginx:
    image: nginx:alpine
    container_name: freshharvest-nginx-prod
    ports:
      - "443:443"  # HTTPS
      - "80:80"     # HTTP redirect
    volumes:
      - ./config/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    restart: always
    depends_on:
      - freshharvest-app
      - monitoring
    networks:
      - freshharvest-prod-network

volumes:
  redis_prod_data:
    driver: local

networks:
  freshharvest-prod-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16
