# FreshHarvest Logging Configuration
# Comprehensive logging setup for all components

version: 1
disable_existing_loggers: false

# Formatters
formatters:
  standard:
    format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
    datefmt: "%Y-%m-%d %H:%M:%S"

  detailed:
    format: "%(asctime)s - %(name)s - %(levelname)s - %(module)s - %(funcName)s - %(lineno)d - %(message)s"
    datefmt: "%Y-%m-%d %H:%M:%S"

  json:
    format: '{"timestamp": "%(asctime)s", "logger": "%(name)s", "level": "%(levelname)s", "module": "%(module)s", "function": "%(funcName)s", "line": %(lineno)d, "message": "%(message)s"}'
    datefmt: "%Y-%m-%d %H:%M:%S"

  simple:
    format: "%(levelname)s - %(message)s"

# Handlers
handlers:
  console:
    class: logging.StreamHandler
    level: INFO
    formatter: standard
    stream: ext://sys.stdout

  file_info:
    class: logging.handlers.RotatingFileHandler
    level: INFO
    formatter: detailed
    filename: logs/info.log
    maxBytes: 10485760  # 10MB
    backupCount: 5
    encoding: utf8

  file_error:
    class: logging.handlers.RotatingFileHandler
    level: ERROR
    formatter: detailed
    filename: logs/error.log
    maxBytes: 10485760  # 10MB
    backupCount: 5
    encoding: utf8

  file_debug:
    class: logging.handlers.RotatingFileHandler
    level: DEBUG
    formatter: detailed
    filename: logs/debug.log
    maxBytes: 10485760  # 10MB
    backupCount: 3
    encoding: utf8

  training_file:
    class: logging.handlers.RotatingFileHandler
    level: INFO
    formatter: json
    filename: logs/training.log
    maxBytes: 52428800  # 50MB
    backupCount: 10
    encoding: utf8

  api_file:
    class: logging.handlers.RotatingFileHandler
    level: INFO
    formatter: json
    filename: logs/api.log
    maxBytes: 20971520  # 20MB
    backupCount: 7
    encoding: utf8

  performance_file:
    class: logging.handlers.RotatingFileHandler
    level: INFO
    formatter: json
    filename: logs/performance.log
    maxBytes: 10485760  # 10MB
    backupCount: 5
    encoding: utf8

# Loggers
loggers:
  # Root logger
  "":
    level: INFO
    handlers: [console, file_info, file_error]
    propagate: false

  # Application loggers
  cvProject_FreshHarvest:
    level: INFO
    handlers: [console, file_info, file_error]
    propagate: false

  cvProject_FreshHarvest.training:
    level: INFO
    handlers: [training_file, console]
    propagate: false

  cvProject_FreshHarvest.api:
    level: INFO
    handlers: [api_file, console]
    propagate: false

  cvProject_FreshHarvest.models:
    level: INFO
    handlers: [file_info, console]
    propagate: false

  cvProject_FreshHarvest.data:
    level: INFO
    handlers: [file_info, console]
    propagate: false

  cvProject_FreshHarvest.utils:
    level: INFO
    handlers: [file_info]
    propagate: false

  # Performance monitoring
  performance:
    level: INFO
    handlers: [performance_file, console]
    propagate: false

  # Third-party loggers
  tensorflow:
    level: WARNING
    handlers: [file_info]
    propagate: false

  keras:
    level: WARNING
    handlers: [file_info]
    propagate: false

  matplotlib:
    level: WARNING
    handlers: [file_info]
    propagate: false

  PIL:
    level: WARNING
    handlers: [file_info]
    propagate: false

  urllib3:
    level: WARNING
    handlers: [file_info]
    propagate: false

  requests:
    level: WARNING
    handlers: [file_info]
    propagate: false

# Root logger configuration
root:
  level: INFO
  handlers: [console, file_info, file_error]